spring:
  application:
    name: flash-sale
  
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:flashsaledb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      database: 0

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    root: INFO
    com.example.flashsale: DEBUG
    org.springframework.data.redis: INFO
    org.springframework.cache: INFO

# Flash Sale Configuration
flash-sale:
  total-tickets: 10
  redis:
    ticket-stock-key: "flash:sale:ticket:stock"
    ticket-sold-key: "flash:sale:ticket:sold"
    user-purchase-key: "flash:sale:user:purchase" 